### ISSUE TITLE
Docs aren't deploying

### ISSUE THREAD

**Issue by jmbhughes** [punch-mission/regularizepsf#91]
Actions seem to be failing right now on the deploy docs task.

**Comment by jmbhughes** [comment]
```
Run jupyter-book build docs/
Running Jupyter-Book v0.15.1
Source Folder: /home/runner/work/regularizepsf/regularizepsf/docs
Config Path: /home/runner/work/regularizepsf/regularizepsf/docs/_config.yml
Output Path: /home/runner/work/regularizepsf/regularizepsf/docs/_build/html
[sphinxcontrib-bibtex] Beware that docutils versions 0.18 and 0.19 (you are running 0.18.1) are known to generate invalid html for citations. If this issue affects you, please use docutils<0.18 (or >=0.20 once released) instead. For more details, see https://sourceforge.net/p/docutils/patches/195/
Running Sphinx v5.0.2
making output directory... done
[etoc] Changing master_doc to 'intro'
checking bibtex cache... out of date
parsing bibtex file /home/runner/work/regularizepsf/regularizepsf/docs/references.bib... parsed 0 entries
myst v0.18.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['colon_fence', 'dollarmath', 'html_admonition', 'linkify', 'substitution'], disable_syntax=[], all_links_external=False, url_schemes=['mailto', 'http', 'https'], ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
myst-nb v0.17.2: NbParserConfig(custom_formats={}, metadata_key='mystnb', cell_metadata_key='mystnb', kernel_rgx_aliases={}, execution_mode='force', execution_cache_path='', execution_excludepatterns=[], execution_timeout=100, execution_in_temp=False, execution_allow_errors=False, execution_raise_on_error=False, execution_show_tb=False, merge_streams=False, render_plugin='default', remove_code_source=False, remove_code_outputs=False, code_prompt_show='Show code cell {type}', code_prompt_hide='Hide code cell {type}', number_source_lines=False, output_stderr='show', render_text_lexer='myst-ansi', render_error_lexer='ipythontb', render_image_options={}, render_figure_options={}, render_markdown_format='commonmark', output_folder='build', append_css=True, metadata_to_fm=False)
Using jupyter-cache at: /home/runner/work/regularizepsf/regularizepsf/docs/_build/.jupyter_cache
[autosummary] generating autosummary for: cite.md, development.md, functional.md, help.md, intro.md, plots.md, quickstart.md, theory.md

Extension error (autoapi.extension):
Handler <function run_autoapi at 0x7ff0ce2bab80> for event 'builder-inited' threw an exception (exception: 'Module' object has no attribute 'doc')
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/autoapi/extension.py", line 153, in run_autoapi
    if sphinx_mapper_obj.load(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/autoapi/mappers/python/mapper.py", line 299, in load
    data = self.read_file(path=path, dir_root=dir_root)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/autoapi/mappers/python/mapper.py", line 316, in read_file
    parsed_data = Parser().parse_file(path)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/autoapi/mappers/python/parser.py", line 41, in parse_file
    return self._parse_file(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/autoapi/mappers/python/parser.py", line 38, in _parse_file
    return self.parse(node)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/autoapi/mappers/python/parser.py", line 265, in parse
    data = parse_func(node)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/autoapi/mappers/python/parser.py", line 240, in parse_module
    "doc": _prepare_docstring(node.doc or ""),
AttributeError: 'Module' object has no attribute 'doc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_book/sphinx.py", line 114, in build_sphinx
    app = Sphinx(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/sphinx/application.py", line 256, in __init__
    self._init_builder()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/sphinx/application.py", line 314, in _init_builder
    self.events.emit('builder-inited')
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/sphinx/events.py", line 102, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function run_autoapi at 0x7ff0ce2bab80> for event 'builder-inited' threw an exception (exception: 'Module' object has no attribute 'doc')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/jupyter-book", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_book/cli/main.py", line 317, in build
    builder_specific_actions(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_book/cli/main.py", line 525, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError: 
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================

[AutoAPI] Reading files... [ 16%] /home/runner/work/regularizepsf/regularizepsf/regularizepsf/exceptions.py
Error: Process completed with exit code 1.
```

**Comment by jmbhughes** [comment]
Likely related to https://github.com/py-pkgs/py-pkgs/issues/129#issuecomment-1774034499

**Comment by jmbhughes** [comment]
The inconsistency is introduced by `sphinx-autoapi`. If I remove that, then I can build the website.

**Comment by jmbhughes** [comment]
I pinned versions as follows:
```
sphinx==5.0.2
jupyter-book==0.15.1
sphinx-autoapi==2.0.1
pydata-sphinx-theme==0.14.1
sphinx-codeautolink==0.15.0
matplotlib
numpy
regularizepsf
jupyter
```

and still get

```
Running Jupyter-Book v0.15.1
Source Folder: /Users/jhughes/Desktop/repos/regularizepsf/docs
Config Path: /Users/jhughes/Desktop/repos/regularizepsf/docs/_config.yml
Output Path: /Users/jhughes/Desktop/repos/regularizepsf/docs/_build/html
[sphinxcontrib-bibtex] Beware that docutils versions 0.18 and 0.19 (you are running 0.18.1) are known to generate invalid html for citations. If this issue affects you, please use docutils<0.18 (or >=0.20 once released) instead. For more details, see https://sourceforge.net/p/docutils/patches/195/
Running Sphinx v5.0.2
making output directory... done
[etoc] Changing master_doc to 'intro'
checking bibtex cache... out of date
parsing bibtex file /Users/jhughes/Desktop/repos/regularizepsf/docs/references.bib... parsed 0 entries
myst v0.18.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['colon_fence', 'dollarmath', 'html_admonition', 'linkify', 'substitution'], disable_syntax=[], all_links_external=False, url_schemes=['mailto', 'http', 'https'], ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
myst-nb v0.17.2: NbParserConfig(custom_formats={}, metadata_key='mystnb', cell_metadata_key='mystnb', kernel_rgx_aliases={}, execution_mode='force', execution_cache_path='', execution_excludepatterns=[], execution_timeout=100, execution_in_temp=False, execution_allow_errors=False, execution_raise_on_error=False, execution_show_tb=False, merge_streams=False, render_plugin='default', remove_code_source=False, remove_code_outputs=False, code_prompt_show='Show code cell {type}', code_prompt_hide='Hide code cell {type}', number_source_lines=False, output_stderr='show', render_text_lexer='myst-ansi', render_error_lexer='ipythontb', render_image_options={}, render_figure_options={}, render_markdown_format='commonmark', output_folder='build', append_css=True, metadata_to_fm=False)
Using jupyter-cache at: /Users/jhughes/Desktop/repos/regularizepsf/docs/_build/.jupyter_cache
[autosummary] generating autosummary for: cite.md, development.md, functional.md, help.md, intro.md, plots.md, quickstart.md, theory.md
[AutoAPI] Reading files... [ 16%] /Users/jhughes/Desktop/repos/regularizepsf/regularizepsf/corrector.py                                                                                                                                             
Extension error (autoapi.extension):
Handler <function run_autoapi at 0x1124fef80> for event 'builder-inited' threw an exception (exception: 'Module' object has no attribute 'doc')
Traceback (most recent call last):
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/autoapi/extension.py", line 153, in run_autoapi
    if sphinx_mapper_obj.load(
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/autoapi/mappers/python/mapper.py", line 299, in load
    data = self.read_file(path=path, dir_root=dir_root)
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/autoapi/mappers/python/mapper.py", line 316, in read_file
    parsed_data = Parser().parse_file(path)
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/autoapi/mappers/python/parser.py", line 41, in parse_file
    return self._parse_file(
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/autoapi/mappers/python/parser.py", line 38, in _parse_file
    return self.parse(node)
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/autoapi/mappers/python/parser.py", line 265, in parse
    data = parse_func(node)
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/autoapi/mappers/python/parser.py", line 240, in parse_module
    "doc": _prepare_docstring(node.doc or ""),
AttributeError: 'Module' object has no attribute 'doc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/jupyter_book/sphinx.py", line 114, in build_sphinx
    app = Sphinx(
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/sphinx/application.py", line 256, in __init__
    self._init_builder()
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/sphinx/application.py", line 314, in _init_builder
    self.events.emit('builder-inited')
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/sphinx/events.py", line 102, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function run_autoapi at 0x1124fef80> for event 'builder-inited' threw an exception (exception: 'Module' object has no attribute 'doc')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/bin/jb", line 8, in <module>
    sys.exit(main())
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/jupyter_book/cli/main.py", line 317, in build
    builder_specific_actions(
  File "/Users/jhughes/Desktop/repos/regularizepsf/venv-docs/lib/python3.10/site-packages/jupyter_book/cli/main.py", line 525, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError: 
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================
```

**Comment by jmbhughes** [comment]
We're going to switch to using pure Sphinx instead of Jupyter-book.
